"""Add is_admin and created_at columns to User model

Revision ID: 235a25bd1a74
Revises: a7a28d17ebef
Create Date: 2025-05-16 21:44:33.998486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235a25bd1a74'
down_revision = 'a7a28d17ebef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
